runtime: nodejs
env: flex
api_version: 1

# f1-micro target
resources:
  cpu: .5
  memory_gb: .9
  disk_size_gb: 10



# can't use min instance 0 with auto scaling...
manual_scaling:
  instances: 1

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

metadata:
  items:
  - key: startup-script
    value: |
      #!/bin/bash
      sudo apt-get update && sudo apt-get upgrade
      sudo apt-get install mongodb -y
  
network:
  forwarded_ports:
    - 3000/tcp
    - 27017/tcp
    - 27018/tcp
    - 6666/tcp
    - 80/tcp
    - 8080/tcp
    - 8888/tcp
   accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT

# Temporary workaround for a Cloud SDK bug.
# Ensures that node_modules directory and any .log files are not uploaded (the
# other entries are the default values for skip_files). This will skip any Unix
# hidden files (such as the .git directory)
skip_files:
 - ^(.*/)?#.*#$
 - ^(.*/)?.*~$
 - ^(.*/)?.*\.py[co]$
 - ^(.*/)?.*/RCS/.*$
 - ^(.*/)?\..*$
 - ^(.*/)?.*/node_modules/.*$
 - ^(.*/)?.*\.log$