runtime: nodejs
env: flex
api_version: 1
service: matheusr-01

# f1-micro target
resources:
  cpu: .5
  memory_gb: .6
  disk_size_gb: 10

# can't use min instance 0 with auto scaling...
manual_scaling:
  instances: 1

# health_check:
#   enable_health_check: True
#   check_interval_sec: 5
#   timeout_sec: 4
#   unhealthy_threshold: 2
#   healthy_threshold: 2

network:
  forwarded_ports:
    - 3000/tcp
    - 28017/tcp
    - 29017/tcp

   # accessConfigs:
   #    - name: External NAT
   #      type: ONE_TO_ONE_NAT

# Temporary workaround for a Cloud SDK bug.
# Ensures that node_modules directory and any .log files are not uploaded (the
# other entries are the default values for skip_files). This will skip any Unix
# hidden files (such as the .git directory)
skip_files:
 - ^(.*/)?#.*#$
 - ^(.*/)?.*~$
 - ^(.*/)?.*\.py[co]$
 - ^(.*/)?.*/RCS/.*$
 - ^(.*/)?\..*$
 - ^(.*/)?.*/node_modules/.*$
 - ^(.*/)?.*\.log$